# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import banks_pb2 as banks__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in banks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BankStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/banks.Bank/Query',
                request_serializer=banks__pb2.QueryRequest.SerializeToString,
                response_deserializer=banks__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Deposit = channel.unary_unary(
                '/banks.Bank/Deposit',
                request_serializer=banks__pb2.DepositRequest.SerializeToString,
                response_deserializer=banks__pb2.DepositResponse.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/banks.Bank/Withdraw',
                request_serializer=banks__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=banks__pb2.WithdrawResponse.FromString,
                _registered_method=True)
        self.PropagateDeposit = channel.unary_unary(
                '/banks.Bank/PropagateDeposit',
                request_serializer=banks__pb2.PropagateDepositRequest.SerializeToString,
                response_deserializer=banks__pb2.PropagateDepositResponse.FromString,
                _registered_method=True)
        self.PropagateWithdraw = channel.unary_unary(
                '/banks.Bank/PropagateWithdraw',
                request_serializer=banks__pb2.PropagateWithdrawRequest.SerializeToString,
                response_deserializer=banks__pb2.PropagateWithdrawResponse.FromString,
                _registered_method=True)


class BankServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateDeposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateWithdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=banks__pb2.QueryRequest.FromString,
                    response_serializer=banks__pb2.QueryResponse.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=banks__pb2.DepositRequest.FromString,
                    response_serializer=banks__pb2.DepositResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=banks__pb2.WithdrawRequest.FromString,
                    response_serializer=banks__pb2.WithdrawResponse.SerializeToString,
            ),
            'PropagateDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateDeposit,
                    request_deserializer=banks__pb2.PropagateDepositRequest.FromString,
                    response_serializer=banks__pb2.PropagateDepositResponse.SerializeToString,
            ),
            'PropagateWithdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateWithdraw,
                    request_deserializer=banks__pb2.PropagateWithdrawRequest.FromString,
                    response_serializer=banks__pb2.PropagateWithdrawResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banks.Bank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banks.Bank', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bank(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banks.Bank/Query',
            banks__pb2.QueryRequest.SerializeToString,
            banks__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banks.Bank/Deposit',
            banks__pb2.DepositRequest.SerializeToString,
            banks__pb2.DepositResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banks.Bank/Withdraw',
            banks__pb2.WithdrawRequest.SerializeToString,
            banks__pb2.WithdrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banks.Bank/PropagateDeposit',
            banks__pb2.PropagateDepositRequest.SerializeToString,
            banks__pb2.PropagateDepositResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateWithdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banks.Bank/PropagateWithdraw',
            banks__pb2.PropagateWithdrawRequest.SerializeToString,
            banks__pb2.PropagateWithdrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
